### ISSUE TITLE
After DSM Update 7.1-42661 Update 2 - operating long, quit normal

### ISSUE THREAD

**Issue by Rips0r** [dtypo/Home-Mode-Switcher-for-Synology-Surveillance-Station#3]
Hello,
the script works fine, but sporadically it takes longer than usual to run.

Normally an execution takes about 30 seconds, in the case of an error several minutes. Sometimes the error occurs only once, sometimes more often in a row. With the following normal execution, everything works perfectly again.

This problem only arose after updating from DSM 7.1 - Update 1 to Update 2.
There are no problems on DSM 6.2.4-25556 - Update 6. (tested on other NAS) 

Unfortunately, reinstalling DSM 7.1 Update 2 after a factory reset did not help.

**Comment by DonPablo1010** [comment]
I faced the same problem. Today i moved the hole thing over to mi rock pi 4c+ with DietPi (Bookworm Debian based). It works. But as i run it in cron now and have the possibility to enable logs with crontab-ui i found out, that stderr gives me always the same error when the script runs:

/path/to/script/homemode_switcher.sh: line 99: route: command not found

Line 99 should be that one:

	interface=$(route|grep default|awk '{print $8}')

Anyone an idea if this could probably be the reason why the script needs longer than expected? Or any idea how to fix this error?

**Comment by DonPablo1010** [comment]
Fixed it by changing line into:

interface=$(ip route|grep default|awk '{print $8}')

ip route works instead of route

**Comment by DonPablo1010** [comment]
I switched it back to synology nas for testing and i can confirm, change of Line 99 did the trick. "route" seems to be slowing down the process, specialy when theskriot runs every minute. Since i changed it to "ip route" i got no more error message from synology nas that a task could'nt run 'cause still running.

**Comment by dtypo** [comment]
I just tested the script even with DSM 7.2 and for now I see no problem.
Have you tried using breakpoints to understand which part of the code is causing long execution time?

**Comment by dtypo** [comment]
Added a timeout of 1 minute for the nmap command. 
This should avoid longer scans.

**Comment by DonPablo1010** [comment]
I think, there’s a small issue in the script. The echo -e "\nHosts found in your network:" and the subsequent for loop should be moved outside the while loop. Otherwise, it will keep printing the message “Hosts found in your network” multiple times during the loop.

Here’s the corrected version of the function:

```
function macs_check_v1()
{	
	matching_macs=0
	ip_pool=$(echo ${SYNO_URL%.*:*}.0/24)
	echo "Scanning hosts in the same network of the Synology NAS..."
	nmap_scan=""
	while [ -z "$nmap_scan" ]; do
		nmap_scan=$(timeout 1m nmap -sn --disable-arp-ping $ip_pool | awk '/MAC/{print $3}')
	done

	echo -e "\nHosts found in your network:"
	for host in $nmap_scan; do
		echo -e "\n$host"
		for authorized_mac in $MACS; do
			if [ "$host" == "$authorized_mac" ]; then
				let "matching_macs+=1"
				echo -e "This MAC address matches with one of the authorized MAC addresses!"
			fi
		done
	done
}
```

With this change, the “Hosts found in your network” message will be printed once after the Nmap scan is completed within the 1-minute timeout. This should work as expected and give the desired result.

**Comment by DonPablo1010** [comment]
Is guess, there’s a small issue in the script now. The echo -e "\nHosts found in your network:" and the subsequent for loop should be moved outside the while loop. Otherwise, it will keep printing the message “Hosts found in your network” multiple times during the loop.

Here’s a corrected version:

```
function macs_check_v1()
{	
	matching_macs=0
	ip_pool=$(echo ${SYNO_URL%.*:*}.0/24)
	echo "Scanning hosts in the same network of the Synology NAS..."
	nmap_scan=""
	while [ -z "$nmap_scan" ]; do
		nmap_scan=$(timeout 1m nmap -sn --disable-arp-ping $ip_pool | awk '/MAC/{print $3}')
	done

	echo -e "\nHosts found in your network:"
	for host in $nmap_scan; do
		echo -e "\n$host"
		for authorized_mac in $MACS; do
			if [ "$host" == "$authorized_mac" ]; then
				let "matching_macs+=1"
				echo -e "This MAC address matches with one of the authorized MAC addresses!"
			fi
		done
	done
}
```

With this change, the “Hosts found in your network” message will be printed once after the Nmap scan is completed within the 1-minute timeout. This should work, but i didn't test it.

**Comment by dtypo** [comment]
> I guess, there’s a small issue in the script now. The echo -e "\nHosts found in your network:" and the subsequent for loop should be moved outside the while loop. Otherwise, it will keep printing the message “Hosts found in your network” multiple times during the loop.
> 
> Here’s a corrected version:
> 
> ```
> function macs_check_v1()
> {	
> 	matching_macs=0
> 	ip_pool=$(echo ${SYNO_URL%.*:*}.0/24)
> 	echo "Scanning hosts in the same network of the Synology NAS..."
> 	nmap_scan=""
> 	while [ -z "$nmap_scan" ]; do
> 		nmap_scan=$(timeout 1m nmap -sn --disable-arp-ping $ip_pool | awk '/MAC/{print $3}')
> 	done
> 
> 	echo -e "\nHosts found in your network:"
> 	for host in $nmap_scan; do
> 		echo -e "\n$host"
> 		for authorized_mac in $MACS; do
> 			if [ "$host" == "$authorized_mac" ]; then
> 				let "matching_macs+=1"
> 				echo -e "This MAC address matches with one of the authorized MAC addresses!"
> 			fi
> 		done
> 	done
> }
> ```
> 
> With this change, the “Hosts found in your network” message will be printed once after the Nmap scan is completed within the 1-minute timeout. This should work, but i didn't test it.

Totally correct, fixed the code, thanks DonPablo1010!

**Comment by DonPablo1010** [comment]
Since the script is probably started by the task scheduler every five minutes, it makes sense to end it after three failed attempts that lasted more than 1 minute.

What do you think of this adaptation?

```
function macs_check_v1()
{
	matching_macs=0
	ip_pool=$(echo ${SYNO_URL%.*:*}.0/24)
	echo "Scanning hosts in the same network of the Synology NAS..."
	nmap_scan=""
	retry_count=0

	while [ -z "$nmap_scan" ]; do
		nmap_scan=$(timeout 1m nmap -sn --disable-arp-ping $ip_pool | awk '/MAC/{print $3}')

		if [ -z "$nmap_scan" ]; then
			let "retry_count+=1"
			if [ "$retry_count" -eq 3 ]; then
				echo "Exceeded maximum retry attempts. Exiting the script due to three failed nmap scans."
				exit 1
			else
				echo "Nmap scan attempt $retry_count failed. Retrying..."
			fi
		fi
	done

	echo -e "\nHosts found in your network:"
	for host in $nmap_scan; do
		echo -e "\n$host"
		for authorized_mac in $MACS; do
			if [ "$host" == "$authorized_mac" ]; then
				let "matching_macs+=1"
				echo -e "This MAC address matches with one of the authorized MAC addresses!"
			fi
		done
	done
}

```
With this modification, the nmap_scan loop will retry up to three times if the scan is aborted due to taking more than one minute. After three failed attempts, the script will exit and echo the appropriate message.
